name: dc1clientflutter
description: A new Flutter application.
publish_to: 'none'
version: 0.3.1+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^0.9.4
  cupertino_icons: ^0.1.2
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.6+2
  dio: ^3.0.9
  provider: ^4.3.1
  fluttertoast: ^3.0.3
  flukit: ^1.0.2
  flutter_socket_plugin: ^1.0.1
  event_bus: ^1.1.1
  flutter_datetime_picker: ^1.3.5
  uuid_enhanced: ^3.0.2
  flutter_bugly: ^0.2.8
  package_info: ^0.4.0+17
  permission_handler: ^5.0.0+hotfix.4
  ota_update: ^2.2.1

  flushbar: ^1.10.4
  nav_router: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - img/
